### ISSUE TITLE
Runtime error regarding unset ${cpu.resource.conversion.id} property

### ISSUE THREAD

**Issue by monaw** [wangso/cipres#4]
When saving a task, the following runtime error shows up in the all-gateway.log:

```
[...]
Jun 06 2019 11:42:24 [exec-9] DEBUG -                  PerlEval:101    | In cleanup
Jun 06 2019 11:42:24 [exec-9] ERROR -                 Workbench:1595   | ${cpu.resource.conversion.id} property is not set.
java.lang.NumberFormatException: For input string: "${cpu.resource.conversion.id}"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:578)
	at java.lang.Long.parseLong(Long.java:631)
	at org.ngbw.sdk.Workbench.getCPUresourceConversionId(Workbench.java:1592)
	at org.ngbw.sdk.tool.TaskInitiate.queueTask(TaskInitiate.java:119)
	at org.ngbw.sdk.Workbench.submitTask(Workbench.java:742)
	at org.ngbw.sdk.Workbench.submitTask(Workbench.java:725)
	at org.ngbw.web.actions.CreateTask.run(CreateTask.java:363)
[...]
```

**Comment by monaw** [comment]
needed to add entries into the resource_conversion database table and then add the following to build.properties:
```
cpu.resource.conversion.id=1
gpu.resource.conversion.id=2
```
but it took several build & deploy for the changes to actually work...hmmm
